### ISSUE TITLE
Losing progress due to networking issues.

### ISSUE THREAD

**Issue by kevinlekiller** [PaulCombal/SteamAppsList#5]
Since all the JSON data is buffered in memory, if a single network issue occurs, the script dies and all the data is lost, which can take hours to collect (which happened, after ~6 hours and ~10k API requests the script died because of a DNS resolving issue -> `FetchError: request to https://store.steampowered.com/api/appdetails/?filters=basic,achievements&appids=1827640 failed, reason: getaddrinfo EAI_AGAIN store.steampowered.com
    at ClientRequest.<anonymous> (/home/kevin/Downloads/SteamAppsList/node_modules/node-fetch/lib/index.js:1491:11)
`).

Dumping the memory to file every once in a while would be preferable.

Currently, I run the saveList function after every API request, reseting the arranged_list variable each time, but this is obviously inneficient, buffering a few hundred requests, then dumping to file would be better.

**Comment by PaulCombal** [comment]
That's true, it was a quick script I put together a while ago. It's not perfect.

I'm not sure if this was available at the time, but the Steamworks web API works well nowadays. [More here.](https://partner.steamgames.com/doc/webapi/ISteamApps)

I'm not sure I will have motivation to improve it myself, but feel free to implement a fix if you wish!

**Comment by wgpierce** [comment]
I saw this error a few times as well, but then it may just go away. If EAI_AGAIN is just like EAGAIN, we can try again right away, and I'm guessing we just need to wrap the code that could throw the exception like so:

```
            let success = false;

            while (!success) {
                try {
                    let response = await fetch(data_url + ids);

                    while (!response.ok) {
                        console.warn('Batch failed, we have to take a break and retry. Code: ' + response.status);
                        console.warn('Url: ', data_url + ids);
                        let timeout = 1000 * 60 * 2; // Too many requests, any random error, wait 2 minutes
                        if (response.status === 502) { // Bad getaway, sometimes occur randomly
                            timeout = 1000;
                        }
                        await timeOutPromise(timeout);
                        response = await fetch(data_url + ids);
                    }
                    success = true;
                } catch (e) {
                    console.warn('Likeley DNS error getaddrinfo EAI_AGAIN, just try again. Error:' + e);
                }
            }
```

**Comment by Tropingenie** [comment]
Another error is ECONNRESET:

```
/home/pon/Programs/SteamAppsList/node_modules/node-fetch/lib/index.js:1461
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://store.steampowered.com/api/appdetails/?filters=achievements,release_date&appids=996850 failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/pon/Programs/SteamAppsList/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at TLSSocket.socketErrorListener (node:_http_client:511:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

I recommend against hardcoding the error message to a specific error since you included the error message anyway:

`console.warn('Network error, just try again. Error: ' + e);`
